/** Auto-generated by scripts/curate-venue-images.mjs — re-run with API keys for more coverage. */
import type { PlaceImageSource } from '../types/placeImage'

export const CURATED_VENUE_IMAGES: Record<string, string> = {
  'cam thanh basket boat':
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Basket_Boat_and_the_Bamboo_forest_%28Unsplash%29.jpg/960px-Basket_Boat_and_the_Bamboo_forest_%28Unsplash%29.jpg',
  'furama city centre':
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/%28SGP-Singapore%29_Furama_City_Centre_2026-02-17.jpg/960px-%28SGP-Singapore%29_Furama_City_Centre_2026-02-17.jpg',
  'little hoi an. a boutique hotel & spa':
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Little_Hoi_An._A_Boutique_Hotel_%26_Spa.jpg/960px-Little_Hoi_An._A_Boutique_Hotel_%26_Spa.jpg',
  'marina bay sands':
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Marina_Bay_Sands_%28Singapore%29.jpg/960px-Marina_Bay_Sands_%28Singapore%29.jpg',
}

export const CURATED_VENUE_ATTRIBUTIONS: Record<string, string> = {}

export const CURATED_VENUE_SOURCES: Record<string, PlaceImageSource> = {
  'cam thanh basket boat': 'curated',
  'furama city centre': 'curated',
  'little hoi an. a boutique hotel & spa': 'curated',
  'marina bay sands': 'curated',
}
